services:
  database:
    container_name: app-database-prod
    image: mysql:5.7
    environment:
      - PRODUCTION_MODE=true
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - web
  api:
    container_name: app-api-prod
    build: ./Api/
    environment:
      - NODE_ENV=${NODE_ENV}
      - PRODUCTION_MODE=true
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_EXPIRATION_DAYS=${TOKEN_EXPIRATION_DAYS}
      - HOSTNAME=${HOSTNAME}
      - PORT=${PORT}
      - ROOT_USER_EMAIL=${ROOT_USER_EMAIL}
      - ROOT_USER_PASSWORD=${ROOT_USER_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
    volumes:
      - ./Api/src:/api/src/
      - ./Api/prisma:/api/prisma/
    depends_on:
      - database
    networks:
      - web
  nginx:
    container_name: app-nginx-prod
    build:
      context: .
      dockerfile: nginx/prod/Dockerfile
    ports:
      - "80:80"
    environment:
      - PRODUCTION_MODE=true
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    depends_on:
      - api
      - database
    networks:
      - web
    restart: always
networks:
  web:
    driver: bridge